---
abstract: 'Try every conceivable way to get full hostname'
author:
  - 'Scott Penrose <scott@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Hostname-Long
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/scottp/sys-hostname-long/
version: 1.5
